tags:
- name: Tasks
  description: Tasks API

paths:
# [GET] tasks
  /tasks:
    get:
      tags:
      - Tasks
      summary: Find Tasks
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] tasks
    post:
      tags:
      - Tasks
      summary: Add Task
      parameters:
      - name: body
        in: body
        description: Task Data
        required: true
        schema:
          $ref: '#/definitions/tasks'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# [GET] tasks/id
  /tasks/{id}:
    get:
      tags:
      - Tasks
      summary: Find Task By Id
      parameters:
      - name: id
        in: path
        description: Task Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] tasks/id
    delete:
      tags:
      - Tasks
      summary: Delete Task By Id
      parameters:
      - name: id
        in: path
        description: Task Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  tasks:
    type: object
    required:
        - title
        - priority
        - description
    properties:
      title:
        type: string
        description: Task title
      priority:
        type: string
        description: Priority level of the task i.e HIGH
      description:
        type: string
        description: Task description

schemes:
 - https
 - http
